"""Fixed-shape continuous operators for PyTorch."""

from .atoms import Atoms
from .geometry import (
    ChartSpec,
    ChartState,
    EuclideanGeometrySpec,
    GeometrySpec,
    GeometryState,
    GridPatternSpec,
    LinePatternSpec,
    PatternSpec,
    PatternState,
    PointsPatternSpec,
    SphereGeometrySpec,
    TorusGeometrySpec,
)
from .geometry import presets as geometry_presets
from .kernels import (
    AmpWidthSpec,
    BandwidthBounds,
    BiweightSpec,
    DirectAmpWidthSpec,
    FixedWidthSpec,
    GaussianSpec,
    KernelOptions,
    KernelSpec,
    LogWidthSpec,
    NormalizationSpec,
    PolarAmpWidthSpec,
    ProfileBinding,
    TriangleSpec,
    TriweightSpec,
    WendlandC2Spec,
    presets,
)
from .nn import CSTConv2d, CSTLinear, CSTModule, NormalizedStripLinear
from .operators import ChartPairSpec, Operator, OperatorSpec, SingleChartSpec
from .optim import CSTOptimizer, OptimizerStateAdapter

__all__ = [
    "AmpWidthSpec",
    "Atoms",
    "BandwidthBounds",
    "BiweightSpec",
    "CSTConv2d",
    "CSTLinear",
    "CSTModule",
    "CSTOptimizer",
    "ChartPairSpec",
    "ChartSpec",
    "ChartState",
    "DirectAmpWidthSpec",
    "EuclideanGeometrySpec",
    "FixedWidthSpec",
    "GaussianSpec",
    "GeometrySpec",
    "GeometryState",
    "GridPatternSpec",
    "KernelOptions",
    "KernelSpec",
    "LinePatternSpec",
    "LogWidthSpec",
    "NormalizationSpec",
    "NormalizedStripLinear",
    "Operator",
    "OperatorSpec",
    "OptimizerStateAdapter",
    "PatternSpec",
    "PatternState",
    "PointsPatternSpec",
    "PolarAmpWidthSpec",
    "ProfileBinding",
    "SingleChartSpec",
    "SphereGeometrySpec",
    "TorusGeometrySpec",
    "TriangleSpec",
    "TriweightSpec",
    "WendlandC2Spec",
    "geometry_presets",
    "presets",
]
