"""Fixed-shape continuous operators for PyTorch."""

from .atoms import Atoms
from .geometry import (
    Chart,
    EuclideanGeometry,
    ExplicitChart,
    Geometry,
    GridPattern,
    LinePattern,
    PointsPattern,
    ProductChart,
    SitePattern,
    SphereGeometry,
    StripChart,
    TorusGeometry,
)
from .kernels import (
    AmpWidthSpec,
    BandwidthBounds,
    BiweightSpec,
    DirectAmpWidthSpec,
    FixedWidthSpec,
    GaussianSpec,
    KernelOptions,
    KernelSpec,
    LogWidthSpec,
    NormalizationSpec,
    PolarAmpWidthSpec,
    ProfileBinding,
    TriangleSpec,
    TriweightSpec,
    WendlandC2Spec,
    presets,
)
from .nn import CSTConv2d, CSTLinear, CSTModule, NormalizedStripLinear
from .operators import ChartPairSpec, Operator, OperatorSpec, SingleChartSpec
from .optim import CSTOptimizer, OptimizerStateAdapter

__all__ = [
    "AmpWidthSpec",
    "Atoms",
    "BandwidthBounds",
    "BiweightSpec",
    "CSTConv2d",
    "CSTLinear",
    "CSTModule",
    "CSTOptimizer",
    "Chart",
    "ChartPairSpec",
    "DirectAmpWidthSpec",
    "EuclideanGeometry",
    "ExplicitChart",
    "FixedWidthSpec",
    "GaussianSpec",
    "Geometry",
    "GridPattern",
    "KernelOptions",
    "KernelSpec",
    "LinePattern",
    "LogWidthSpec",
    "NormalizationSpec",
    "NormalizedStripLinear",
    "Operator",
    "OperatorSpec",
    "OptimizerStateAdapter",
    "PointsPattern",
    "PolarAmpWidthSpec",
    "ProductChart",
    "ProfileBinding",
    "SingleChartSpec",
    "SitePattern",
    "SphereGeometry",
    "StripChart",
    "TorusGeometry",
    "TriangleSpec",
    "TriweightSpec",
    "WendlandC2Spec",
    "presets",
]
