"""Public CST optimizer families and their reusable N/D components."""

from .adamr import CSTAdamR
from .atom_grad import (
    AtomGradientObservation,
    AtomGradRequest,
    CurvatureBlockMask,
    CurvatureBlockMode,
    LinearJGAtomGrad,
    LinearJGHAtomGrad,
)
from .config import (
    AdamRConfig,
    AdamWConfig,
    NormalizedOptimizerConfig,
    QuadraticOptimizerConfig,
)
from .dense import DenseAdamWProposal, DenseAdamWState, FunctionalAdamW
from .moments import (
    DenominatorMoment,
    DenominatorMomentState,
    DenominatorPolynomial,
    ExpandedDenominatorMoment,
    ExpandedNormalizedMoments,
    ExpandedNumeratorMoment,
    ExpandedUnitDenominator,
    MomentContext,
    NormalizedMomentSystem,
    NormalizedMomentSystemState,
    NumeratorMoment,
    NumeratorMomentState,
    UnitDenominator,
    UnitDenominatorState,
)
from .normalized_optimizer import (
    CSTSGD,
    CSTImplicitAdam,
    CSTMomentum,
    CSTNormalizedAdam,
    CSTNormalizedMomentum,
    CSTNormalizedRMSProp,
    CSTNormalizedSGD,
    CSTRMSProp,
)
from .optimizer import CSTStepResult
from .parameter import CSTParameterAdam, ParameterAdamConfig
from .quadratic_optimizer import (
    CSTQuadraticAdam,
    CSTQuadraticMomentum,
    CSTQuadraticRMSProp,
    CSTQuadraticSGD,
)
from .solvers import (
    NormalizedBoxFixedPointSolver,
    NormalizedEvaluation,
    NormalizedFixedPointSolver,
    NormalizedSolver,
    NormalizedSolveResult,
    NormalizedUpdateProblem,
    QuadraticBoxGradientSolver,
    QuadraticGradientSolver,
    QuadraticTrustSolver,
)

__all__ = [
    "CSTSGD",
    "AdamRConfig",
    "AdamWConfig",
    "AtomGradRequest",
    "AtomGradientObservation",
    "CSTAdamR",
    "CSTImplicitAdam",
    "CSTMomentum",
    "CSTNormalizedAdam",
    "CSTNormalizedMomentum",
    "CSTNormalizedRMSProp",
    "CSTNormalizedSGD",
    "CSTParameterAdam",
    "CSTQuadraticAdam",
    "CSTQuadraticMomentum",
    "CSTQuadraticRMSProp",
    "CSTQuadraticSGD",
    "CSTRMSProp",
    "CSTStepResult",
    "CurvatureBlockMask",
    "CurvatureBlockMode",
    "DenominatorMoment",
    "DenominatorMomentState",
    "DenominatorPolynomial",
    "DenseAdamWProposal",
    "DenseAdamWState",
    "ExpandedDenominatorMoment",
    "ExpandedNormalizedMoments",
    "ExpandedNumeratorMoment",
    "ExpandedUnitDenominator",
    "FunctionalAdamW",
    "LinearJGAtomGrad",
    "LinearJGHAtomGrad",
    "MomentContext",
    "NormalizedBoxFixedPointSolver",
    "NormalizedEvaluation",
    "NormalizedFixedPointSolver",
    "NormalizedMomentSystem",
    "NormalizedMomentSystemState",
    "NormalizedOptimizerConfig",
    "NormalizedSolveResult",
    "NormalizedSolver",
    "NormalizedUpdateProblem",
    "NumeratorMoment",
    "NumeratorMomentState",
    "ParameterAdamConfig",
    "QuadraticBoxGradientSolver",
    "QuadraticGradientSolver",
    "QuadraticOptimizerConfig",
    "QuadraticTrustSolver",
    "UnitDenominator",
    "UnitDenominatorState",
]
